/camera_node:
  ros__parameters:
    camera_info_url: package://rm_vision_bringup/config/camera_info.yaml
    exposure_time: 500
    gain: 16.0

# 串口节点
/serial_driver:
  ros__parameters:
    timestamp_offset: 0.0055     #串行通信驱动的时间戳偏移量
    device_name: /dev/ttyACM0 #串行通信驱动的设备名称
    baud_rate: 460800 #串行通信驱动的波特率设置
    flow_control: none  #串行通信驱动的流控制设置
    parity: none  #串行通信驱动的奇偶校验设置
    stop_bits: "1"    #串行通信驱动的停止位设置

# 装甲板识别节点
/armor_detector:
  ros__parameters:
    debug: true

    detect_color: 1 # 0: red, 1: blue
    binary_thres: 85

    light.min_ratio: 0.1  # 灯条 (长/宽) 的比值 Detector::isLight 函数中判断是否为灯条
    armor.min_light_ratio: 0.8  # 装甲板 (长/宽) 的比值 Detector::isArmor 函数中判断是否为装甲板

    classifier_threshold: 0.6
    ignore_classes: ["negative"]

# 装甲板观测节点
/armor_tracker:
  ros__parameters:
    target_frame: gimbal_odom # 目标坐标系
    max_armor_distance: 10.0  # 极限最远可观测装甲板距离

    ekf:
      sigma2_q_xyz: 0.05 # 位置坐标过程噪声方差
      sigma2_q_yaw: 5.0 #偏航角过程噪声方差
      sigma2_q_r: 80.0 #位置坐标过程噪声方差

      r_xyz_factor: 0.00025   #位置坐标观测噪声协方差系数
      r_yaw: 0.005 #偏航角观测噪声协方差

    tracker:  #标记{tracker 参数}
      max_match_distance: 0.5
      max_match_yaw_diff: 1.0

  # 注意: 弹道解算的参数也在这里
      k: 0.038
      bias_time: 10
      s_bias: 0.18375
      z_bias: 0.0

      tracking_thres: 5
      lost_time_thres: 1.0